# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:

  nginx:
    container_name: nginx-angular-jumpstart
    image: nginx-angular-jumpstart
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
